### ISSUE TITLE
Memory usage keeps increasing if FS is enabled

### ISSUE THREAD

**Issue by cant89** [fullstorydev/fullstory-browser-sdk#180] opened 2023-08-02 13:01 UTC
Hi,

we have noticed that the memory of the Main thread (Chrome dev tools -> memory) keeps increasing if Fullstory is enabled.

Every time the user interact with the platform, the memory usage increases - which is normal because rendering and other operations are being performed - but when the garbage collector clean it up it the memory does not goes back to its previous value.

For example, by clicking around opening popovers, drawers and especially changing route of our React SPA, its just a matter of 20-30 clicks to see the memory usage going from ~60 MB to ~300 MB (after having forced the cleanup of the garbage collector).

Please be aware that this is a critical issue that our customers are facing in production which makes the browser window crashes entirely (showing "Aw, Snap!").

Our configuration is as simple as `FullStory.init({ orgId: '12345' })` in the root index.js.

Thanks

**Comment by rcmaples** [comment] 2023-08-02 16:03
hey @cant89 — RC here with FullStory's support engineering team. We received a support email with the details above. I wanted to acknowledge it and let you know we're investigating the issue. I'll follow up in the email thread. Cheers!

**Comment by rcmaples** [comment] 2023-08-02 18:38
hey @cant89 — I haven't heard back in the email thread, but we think we found the issue. We've just pushed the fix to production a few minutes ago. Things should start looking better and stop crashing the browser. Let me know if the issue persists!

**Comment by rcmaples** [comment] 2023-08-03 12:25
@cant89 — Woohoo! That's great to hear 🥳
Terribly sorry for the issue; we strive not to have any perf impact like this. We introduced some changes on Monday the 31st that caused the issue. We identified the root cause as a failure to free instance hooks added to `<input>` elements in a React-specific path in our capture script (fs.js). We rolled those changes back yesterday while we continued to investigate.

Engineering is working on a patch that will be released later today that will resolve the issue. I'd love to coordinate with you after the deployment to double-check that the perf issues don't come back. Would you mind to write in to support@fullstory.com, mentioning me and this issue?
I'd like to attach it to the existing ticket and take our coordination efforts into that channel. 

Alas, with regards to the changelog, we don't have public release notes or changelogs available for our capture script.

**Comment by cant89** [comment] 2023-08-03 13:11
Sure, just sent an email. 
Thanks for the clarification!

**Closed** 2023-09-20 08:30 UTC
